### ISSUE TITLE
conn.writeCoroutine() Timer not reset

### ISSUE THREAD

**Issue by M6ZeroG** [9b9387/zero#4]
https://github.com/9b9387/zero/blob/587198b68c4a0e65ec45355d89dad25ba98610fd/conn.go#L86-L89

Need to add a line of code here to reset the `hbTimer` like this:
```
c.hbTimer.Reset(c.hbInterval)
```

**Comment by 9b9387** [comment]
you are right. I write hbTimer.Reset in readCoroutine method. your way is better.
