### ISSUE TITLE
读取协程中的超时定时问题

### ISSUE THREAD

**Issue by tiger7chan** [9b9387/zero#5]
`
func (c *Conn) readCoroutine(ctx context.Context) {

	for {
		select {
		case <-ctx.Done():
			return

		default:
			// 设置超时
			if c.hbInterval > 0 {
				err := c.rawConn.SetReadDeadline(time.Now().Add(c.hbTimeout))
				if err != nil {
					c.done <- err
					continue
				}
			}
....
`
这里的c.hbInterval 应该是c.hbTimeout这个超时吧？

**Comment by 9b9387** [comment]
这里其实是个特殊设置。hbInterval==0的时候不做心跳检测。
